logging:
    level:
        blog: WARN
        org: WARN
#        org.hibernate.SQL: DEBUG
#        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
        org.springframework.security: DEBUG
spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: 12345
        url: jdbc:mysql://localhost:3306/nlt_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
    sql:
        init:
            mode: always
    jpa:
        hibernate:
            ddl-auto: create-drop
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
#        database-platform: org.hibernate.dialect.MySQL8Dialect
